const types = {
    RESET: "RESET",
    FETCH_POSTS: "FETCH_POSTS",
    GET_SINGLE_POST: "GET_SINGLE_POST",
    UPDATE_POST: "UPDATE_POST",
    DELETE_POST: "DELETE_POST",
    POST_ERROR: "POST_ERROR",
    CREATE_POST: "CREATE_POST",
    ADD_POST_TO_USER: "ADD_POST_TO_USER",
    FETCH_SINGLE_POST: "FETCH_SINGLE_POST",
    TOGGLE_MODAL: "TOGGLE_MODAL"
}

export default types;