const CommentTypes = {
    RESET: "RESET_COMMENTS",
    FETCH_COMMENTS: "FETCH_COMMENTS",
    GET_SINGLE_COMMENT: "GET_SINGLE_COMMENT",
    UPDATE_COMMENT: "UPDATE_COMMENT",
    DELETE_COMMENT: "DELETE_COMMENT",
    COMMENT_ERROR: "COMMENT_ERROR",
    CREATE_COMMENT: "CREATE_COMMENT",
    FETCH_SINGLE_COMMENT: "FETCH_SINGLE_COMMENT",
    TOGGLE_MODAL: "COMMENT/TOGGLE_MODAL"
}

export default CommentTypes;